# Generated by Django 3.1.5 on 2021-07-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeronine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='extra_cost',
            field=models.IntegerField(),
        ),
    ]
