# Generated by Django 3.1.5 on 2021-10-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeronine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='extra_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='option_code',
            field=models.ForeignKey(blank=True, db_column='option_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='zeronine.option'),
        ),
        migrations.AlterField(
            model_name='value',
            name='product_code',
            field=models.ForeignKey(blank=True, db_column='product_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='zeronine.product'),
        ),
    ]
