# Generated by Django 3.1.5 on 2021-11-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeronine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joindetail',
            name='address',
        ),
        migrations.RemoveField(
            model_name='joindetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='joindetail',
            name='phone',
        ),
    ]
