# Generated by Django 3.1.5 on 2021-07-21 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeronine', '0002_auto_20210721_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['option_code']},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['value_code']},
        ),
    ]
