# Generated by Django 3.1.5 on 2021-11-17 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zeronine', '0002_auto_20211117_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='joindetail',
            name='address',
            field=models.CharField(db_column='address', default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joindetail',
            name='name',
            field=models.CharField(db_column='name', default=2, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joindetail',
            name='phone',
            field=models.CharField(db_column='phone', default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
