# Generated by Django 3.1.5 on 2021-11-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeronine', '0003_auto_20211117_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joindetail',
            name='address',
            field=models.CharField(db_column='address', default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='joindetail',
            name='name',
            field=models.CharField(db_column='name', default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='joindetail',
            name='phone',
            field=models.CharField(db_column='phone', default='', max_length=64),
        ),
    ]
