# Generated by Django 3.1.5 on 2021-11-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeronine', '0003_auto_20211109_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='extra_cost',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
