# Generated by Django 3.1.5 on 2021-07-28 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeronine', '0004_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='value_code',
            field=models.ForeignKey(blank=True, db_column='value_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='zeronine.value'),
        ),
    ]
