# Generated by Django 3.1.5 on 2021-08-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeronine', '0005_auto_20210728_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['post_code']},
        ),
        migrations.AlterModelOptions(
            name='zzim',
            options={'ordering': ['zzim_code']},
        ),
        migrations.AlterField(
            model_name='joindetail',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
