# Generated by Django 3.1.5 on 2021-08-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeronine', '0006_auto_20210810_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joindetail',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
