# Generated by Django 3.1.5 on 2021-08-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeronine', '0007_auto_20210810_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kakao_link',
            field=models.CharField(db_index=True, default='', max_length=200),
        ),
    ]
