# Generated by Django 3.1.5 on 2021-08-19 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeronine', '0008_product_kakao_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='product_code',
            field=models.ForeignKey(db_column='product_code', default=1, on_delete=django.db.models.deletion.CASCADE, to='zeronine.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='kakao_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
