# Generated by Django 3.1.5 on 2021-08-21 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeronine', '0009_auto_20210819_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='product_code',
        ),
        migrations.AddField(
            model_name='joindetail',
            name='element_code',
            field=models.ForeignKey(db_column='element_code', default=935, on_delete=django.db.models.deletion.CASCADE, to='zeronine.element'),
            preserve_default=False,
        ),
    ]
