# Generated by Django 3.1.5 on 2021-08-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zeronine', '0010_auto_20210821_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joindetail',
            name='element_code',
        ),
    ]
