# Generated by Django 3.1.5 on 2021-08-22 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeronine', '0012_joindetail_value_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joindetail',
            name='value_code',
            field=models.ForeignKey(db_column='value_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='zeronine.value'),
        ),
    ]
