# Generated by Django 3.1.5 on 2021-08-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zeronine', '0014_auto_20210822_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joindetail',
            name='value_code',
            field=models.ForeignKey(db_column='value_code', default=1, on_delete=django.db.models.deletion.CASCADE, to='zeronine.value'),
            preserve_default=False,
        ),
    ]
